name: Optimized CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Build Files
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Application
        run: |
          mkdir -p build
          echo "Compiling application..."
          sleep 2
          echo "Build Complete" > build/output.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: |
          echo "Running tests..."
          sleep 1
          echo "Tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging..."
          sleep 2
          echo "Deployment Successful!"

      - name: Auto-Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed! Rolling back..."
          sleep 2
          echo "Rollback complete."

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

