name: Optimized CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build & Cache Dependencies
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm  # Cache node modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  # Job 2: Parallel Testing (Unit & Integration)
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test-type: [unit, integration]  # Running tests in parallel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run ${{ matrix.test-type }} Tests
        run: npm test -- ${{ matrix.test-type }}

  # Job 3: Deployment with Auto Rollback
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying application..."
          # Simulated deployment step
          sleep 3
          echo "Deployment Complete"

      - name: Verify Deployment
        run: |
          echo "Running post-deployment checks..."
          # Simulating a failure scenario
          exit 1

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          # Simulated rollback command
          echo "Rollback complete!"
